---
- name: Deploy ec2 instances
  hosts: localhost
  gather_facts: false

  tasks:    
         
    - name: Run Terraform
      community.general.terraform:
        project_path: "{{ src_main_tf }}"
        state: present  
        force_init: true
        backend_config:
          bucket: "{{ terraform_backend_bucket }}"
          key: "{{ terraform_backend_key }}"
          region: "{{ terraform_backend_region }}"
      register: terraform_output