---
- name: Deploy ec2 instances
  hosts: localhost
  gather_facts: false

  tasks:    
    - name: Populate terraform.tfvars from Ansible variables
      template:
        src: "{{ tp_tfvars }}"
        dest: "{{ src_main_tfvars }}"
      vars:
        key_name: "{{ key_name }}"
        security_group_ids: "{{ security_group_ids }}"
        vpc_id: "{{ vpc_id }}"
        subnet_id: "{{ subnet_id }}"
        instance_count: "{{ instance_count }}"
        instance_type: "{{ instance_type }}"
        ami_id: "{{ ami_id }}"
        
    - name: Run Terraform
      community.general.terraform:
        project_path: "{{ src_main_tf }}"
        backend_config:
          bucket: "{{ terraform_backend_bucket }}"
          key: "{{ terraform_backend_key }}"
          region: "{{ terraform_backend_region }}"
      register: terraform_output