---
- name: Deploy ec2 instances
  hosts: localhost
  gather_facts: false

  tasks:    
    - name: Add or update variables in terraform.tfvars
      lineinfile:
        path: "{{ src_main_tfvars }}"
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_dict:
        - { key: "vpc_id", value: "{{ vpc_id }}" }
        - { key: "subnet_id", value: "{{ subnet_id }}" }
        - { key: "instance_count", value: "{{ instance_count }}" }
        - { key: "instance_type", value: "{{ instance_type }}" }
        - { key: "ami_id", value: "{{ ami_id }}" }
      when: item.value is defined

    - name: Run Terraform
      community.general.terraform:
        project_path: "{{ src_main_tf }}"
        backend_config:
          bucket: "{{ terraform_backend_bucket }}"
          key: "{{ terraform_backend_key }}"
          region: "{{ terraform_backend_region }}"
      register: terraform_output