---
- name: Execute Terraform
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Run Terraform
      community.general.terraform:
        #provider_upgrade: true
        state: absent  # Indicates you want to destroy Terraform configurations
        force_init: true
        project_path: "{{ src_main_tf }}"
        backend_config:
          bucket: "{{ terraform_backend_bucket }}"
          key: "{{ terraform_backend_key }}"
          region: "{{ terraform_backend_region }}"
      register: terraform_output

    - debug:
        var: terraform_output